import {it,expect,afterEach} from 'vitest';
import {generateKeyPairSync,sign} from 'node:crypto';
import {mkdtempSync,rmSync,readdirSync,readFileSync,writeFileSync,mkdirSync,symlinkSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {encodeLocalRecord} from '../data-os/local-record';
import {commitment,verifyApproval,type AuthorityKey} from './authority';
import {refreshOnce} from './refresh';
const at='2026-09-29T12:00:00.000Z',end='2026-10-01T00:00:00.000Z';
const roots:string[]=[];const temp=()=>{const p=mkdtempSync(join(tmpdir(),'esm-operations-test-'));roots.push(p);return p;};
afterEach(()=>roots.splice(0).forEach(p=>rmSync(p,{recursive:true,force:true})));
function signed(){const pair=generateKeyPairSync('ed25519'),target={selected:'one'},body={schema:'payload.industrial-approval.v1' as const,decisionId:'decision:test',action:'ADMIT' as const,
 authorityId:'role:test-steward',keyId:'key:test',targetDigest:commitment(target),issuedAt:at,notAfter:end};
 const key:AuthorityKey={keyId:body.keyId,authorityId:body.authorityId,publicKeyPem:pair.publicKey.export({type:'spki',format:'pem'}).toString(),actions:['ADMIT','RELEASE'],notBefore:at,notAfter:end,revoked:false};
 return {target,key,approval:{...body,signature:sign(null,encodeLocalRecord(body),pair.privateKey).toString('base64url')}};}
it('verifies an external key decision, not a method label',()=>{const x=signed();expect(verifyApproval(x.approval,'ADMIT',x.target,[x.key],at).authorityId).toBe(x.key.authorityId);});
it.each(['changed-bytes','wrong-action','unknown-key','revoked-key','expired','future','wrong-signer','method-authority','duplicate-key'])(`refuses %s`,kind=>{
 const x=signed();let keys=[x.key],now=at,action:'ADMIT'|'RELEASE'='ADMIT';
 if(kind==='changed-bytes')x.target.selected='other';if(kind==='wrong-action')action='RELEASE';if(kind==='unknown-key')keys=[];
 if(kind==='revoked-key')x.key.revoked=true;if(kind==='expired')now=end;if(kind==='future')now='2026-09-29T11:59:00.000Z';
 if(kind==='wrong-signer')x.approval.signature='A'.repeat(86);if(kind==='method-authority')x.key.authorityId='notationsos.worker';if(kind==='duplicate-key')keys=[x.key,x.key];
 expect(()=>verifyApproval(x.approval,action,x.target,keys,now)).toThrow();
});
const schedule=()=>({schema:'payload.capture-schedule.v1',scheduleId:'port-review',sourceId:'industrial-noaa-usgs',minimumIntervalHours:1,notBefore:at,notAfter:end,maxRuns:2,enabled:true});
const result={captureDigest:commitment('capture'),reviewDigest:commitment('review'),compiledDigest:commitment('compiled'),canonicalAdmission:false as const,release:null};
it('writes intent before execution and retains a bounded success',async()=>{const root=temp();let seen=false;
 const r=await refreshOnce({root,schedule:schedule(),operation:{id:'operation:test'},now:()=>at,execute:async path=>{seen=readFileSync(join(path,'intent.json'),'utf8').includes('industrial-refresh-intent');return result;}});
 expect(seen).toBe(true);expect(r.receipt?.state).toBe('CAPTURED');expect(r.receipt?.result?.canonicalAdmission).toBe(false);
 const retry=await refreshOnce({root,schedule:schedule(),operation:{id:'operation:test'},now:()=>at,execute:async()=>{throw new Error('must not run');}});
 expect(retry.plan.decision).toBe('NOT_DUE');expect(readdirSync(join(root,'port-review','attempts'))).toHaveLength(1);
});
it('failure spends its slot and does not copy raw errors',async()=>{const root=temp(),s={...schedule(),maxRuns:1};
 const r=await refreshOnce({root,schedule:s,operation:{},now:()=>at,execute:async()=>{throw new Error('SECRET Bearer PRIVATE');}});
 expect(r.receipt?.state).toBe('FAILED');expect(JSON.stringify(r)).not.toMatch(/SECRET|PRIVATE|Bearer/);
 const next=await refreshOnce({root,schedule:s,operation:{},now:()=>end,execute:async()=>result});expect(next.plan.decision).toBe('RUN_BUDGET_SPENT');
});
it('disabled schedule never invokes a process',async()=>{let calls=0;const r=await refreshOnce({root:temp(),schedule:{...schedule(),enabled:false},operation:{},now:()=>at,execute:async()=>{calls++;return result;}});expect(calls).toBe(0);expect(r.plan.decision).toBe('DISABLED');});
it('an enable toggle preserves the same immutable schedule budget',async()=>{const root=temp();for(const enabled of [false,true])await refreshOnce({root,schedule:{...schedule(),enabled},operation:{},now:()=>at,execute:async()=>result});expect(readdirSync(join(root,'port-review','attempts'))).toHaveLength(1);});
it.each(['budget','operation','window'])('cannot reset history through changed %s',async kind=>{const root=temp();await refreshOnce({root,schedule:schedule(),operation:{},now:()=>at,execute:async()=>result});
 const s=schedule();if(kind==='budget')s.maxRuns=3;if(kind==='window')s.notBefore='2026-09-28T12:00:00.000Z';
 await expect(refreshOnce({root,schedule:s,operation:kind==='operation'?{changed:true}:{},now:()=>at,execute:async()=>result})).rejects.toThrow();
});
it('an incomplete run blocks all future attempts',async()=>{const root=temp();let n=0;
 await expect(refreshOnce({root,schedule:schedule(),operation:{},now:()=>++n===1?at:'invalid',execute:async()=>result})).rejects.toThrow();
 const r=await refreshOnce({root,schedule:schedule(),operation:{},now:()=>at,execute:async()=>result});expect(r.plan.decision).toBe('HISTORY_INCOMPLETE');
});
it('simultaneous runners cannot spend the same slot',async()=>{const root=temp();let release:()=>void=()=>{};const wait=new Promise<void>(r=>{release=r;});
 const first=refreshOnce({root,schedule:schedule(),operation:{},now:()=>at,execute:async()=>{await wait;return result;}});
 await expect(refreshOnce({root,schedule:schedule(),operation:{},now:()=>at,execute:async()=>result})).rejects.toThrow('REFRESH_LOCKED');release();await first;
});
it('receipt tampering stops collection',async()=>{const root=temp();const r=await refreshOnce({root,schedule:schedule(),operation:{},now:()=>at,execute:async()=>result});
 const f=join(root,'port-review','attempts',r.attemptId!,'receipt.json');const j=JSON.parse(readFileSync(f,'utf8'));j.intentDigest=commitment('wrong');writeFileSync(f,JSON.stringify(j));
 await expect(refreshOnce({root,schedule:schedule(),operation:{},now:()=>at,execute:async()=>result})).rejects.toThrow('RECEIPT_HASH_MISMATCH');
});
it('symlinked state directories are rejected',async()=>{const root=temp(),other=temp();mkdirSync(join(root,'port-review'));symlinkSync(other,join(root,'port-review','attempts'));
 await expect(refreshOnce({root,schedule:schedule(),operation:{},now:()=>at,execute:async()=>result})).rejects.toThrow('UNSAFE_REFRESH_ROOT');
});
